# Update commit status in GitHub
updateCommitStatus: &UPDATE_COMMIT_STATUS
  onStart:
    - update_commit_status validatePluginCriteria --context "$step_name"
  onComplete:
    - update_commit_status validatePluginCriteria --context "$step_name"

resources:
  - name: validatePluginCriteria
    type: GitRepo
    configuration:
      path: Or-Gabay/jfrog-cli-plugins-reg
      gitProvider: github
      buildOn:
        commit: false
        pullRequestCreate: true
      branches:
        include: master
      files:
        include: ^plugins\/.+
pipelines:
  - name: validate_plugin_criteria
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
      environmentVariables:
        readOnly:
          #GOPROXY: https://gocenter.io
          CI: "true"
    steps:
      # Repositories creators tests - should be running in serial
      - name: SearchPluginsYaml
        type: Bash
        configuration:
          integrations:
            - name: or_github
          inputResources:
            - name: validatePluginCriteria
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - go run ./pullrequestvalidation/src/cmds/searchyml/searchyml.go