# Update commit status in GitHub
updateCommitStatus: &UPDATE_COMMIT_STATUS
  onStart:
    - update_commit_status jfrog-cli-plugins-reg --context "$step_name"
  onComplete:
    - update_commit_status jfrog-cli-plugins-reg --context "$step_name"

resources:
  - name: jfrog-cli-plugins-reg
    type: GitRepo
    configuration:
      path: Or-Gabay/jfrog-cli-plugins-reg
      gitProvider: or_cli_github
      buildOn:
        commit: false
        pullRequestCreate: true
      branches:
        include: master
      files:
        include: ^plugins\/.+
pipelines:
  - name: validate_plugin_criteria
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
      environmentVariables:
        readOnly:
          #GOPROXY: https://gocenter.io
          CI: "true"
    steps:
      - name: SearchPluginsYaml
        type: Bash
        configuration:
          integrations:
            - name: or_github
          inputResources:
            - name: jfrog-cli-plugins-reg
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - echo $res_jfrog-cli-plugins-reg_resourcePath
            - cd $res_jfrog-cli-plugins-reg_resourcePath
            - go get gopkg.in/yaml.v2
            - OUTPUT=$(go run "./pipelinesScripts/validation/yaml.go" ContainYamls)
            - add_run_variables yaml_files_path=$OUTPUT
      - name: ValidatePluginsYaml
        type: Bash
        configuration:
          integrations:
            - name: or_github
          inputResources:
            - name: jfrog-cli-plugins-reg
          inputSteps:
            - name: SearchPluginsYaml
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jfrog-cli-plugins-reg_resourcePath/pipelinesScripts/validation
            - go get gopkg.in/yaml.v2
            - go run yaml.go YamlContent
