# Update commit status in GitHub
updateCommitStatus: &UPDATE_COMMIT_STATUS
  onStart:
    - update_commit_status validatePluginCriteria --context "$step_name"
  onComplete:
    - update_commit_status validatePluginCriteria --context "$step_name"

resources:
  - name: buildJfrogCliPluginGit
    type: GitRepo
    configuration:
      path: jfrog/jfrog-cli-plugins-reg
      gitProvider: github
      buildOn:
        # Build on commit and tags
        tagCreate: true
      branches:
        # Only build on the master
        include: master
      files:
        include: ^plugins\/.+
  -name: validatePluginCriteria
    type: GitRepo
    configuration:
      path: jfrog/jfrog-cli-plugins-reg
      gitProvider: github
      buildOn:
        commit: false
        pullRequestCreate: true

pipelines:
  - name: build_jfrog_cli_plugin
    steps:
      - name: BuildAndPush
        type: Bash
        configuration:
          integrations:
            - name: releases_jfrog
          inputResources:
            - name: buildJfrogCliPluginGit
          runtime:
            type: image
            image:
              auto:
                language: go
                versions:
                  - "1.14.4"
          environmentVariables:
            CI: "true"
            JFROG_CLI_PLUGINS_REGISTRY_URL: "https://releases.jfrog.io/artifactory"
            JFROG_CLI_PLUGINS_REGISTRY_REPO: "jfrog-cli-plugins"
            JFROG_CLI_PLUGIN_PLUGIN_NAME: "hello-frog"
            JFROG_CLI_PLUGIN_DOMAIN_NAME: "jfrog"
            JFROG_CLI_PLUGIN_REPO_NAME: "jfrog-cli-plugin-template"
            JFROG_CLI_PLUGIN_VERSION: "v0.1.0"
        execution:
          onStart:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"
          onExecute:
            # Clone plugin repo.
            - git clone https://github.com/$JFROG_CLI_PLUGIN_DOMAIN_NAME/$JFROG_CLI_PLUGIN_REPO_NAME
            # Copy the plugin release script from registry repo to plugin repo.
            - cp "$res_buildJfrogCliPluginGit_resourcePath/pipelinesScripts/pluginRelease.sh" "./$JFROG_CLI_PLUGIN_REPO_NAME/"
            - pushd $JFROG_CLI_PLUGIN_REPO_NAME
            - sh "./pluginRelease.sh"
            - popd
          onComplete:
            - update_commit_status buildJfrogCliPluginGit --context "$step_name"

  - name: validate_plugin_criteria
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
      environmentVariables:
        readOnly:
          #GOPROXY: https://gocenter.io
          CI: "true"
    steps:
      # Repositories creators tests - should be running in serial
      - name: Search plugin's yaml
        type: Bash
        configuration:
          inputResources:
            - name: validatePluginCriteria
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_validatePluginCriteria_resourcePath
            - [ "$(ls -A | grep -i \\.yml\$)" ]
