# Update commit status in GitHub
updateCommitStatus: &UPDATE_COMMIT_STATUS
  onStart:
    - update_commit_status jfrog_cli_plugins_reg_git --context "$step_name"
  onComplete:
    - update_commit_status jfrog_cli_plugins_reg_git --context "$step_name"

commonConfiguration: &COMMON_CONFIGURATION
  inputResources:
    - name: jfrogCliGit

resources:
  - name: jfrog_cli_plugins_reg_git
    type: GitRepo
    configuration:
      path: jfrog/jfrog-cli-plugins-reg
      gitProvider: github
      buildOn:
        commit: false
        pullRequestCreate: true
      branches:
        include: master
      files:
        include: ^plugins\/.+

pipelines:
  - name: plugin_validation
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: releases-docker.jfrog.io/jfrog-ecosystem-integration-env
            tag: 1.0.0
    steps:
      # Validate PR contains only the plugin descriptor
      - name: Structure
        type: Bash
        configuration:
          <<: *COMMON_CONFIGURATION
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jfrog_cli_plugins_reg_git_resourcePath/pipelinesScripts/pluginsvalidation
            - go run validator.go extension

      # Validate plugin descriptor yml
      - name: Descriptor
        type: Bash
        configuration:
          <<: *COMMON_CONFIGURATION
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jfrog_cli_plugins_reg_git_resourcePath/pipelinesScripts/pluginsvalidation
            - go run validator.go structure

      # Run `go vet ./...` and `go test ./...`
      - name: Tests
        type: Bash
        configuration:
          <<: *COMMON_CONFIGURATION
        execution:
          <<: *UPDATE_COMMIT_STATUS
          onExecute:
            - cd $res_jfrog_cli_plugins_reg_git_resourcePath/pipelinesScripts/pluginsvalidation
            - go run yaml.go tests
