name: "CLA Assistant"
on:
  # issue_comment triggers this action on each comment on issues and pull requests
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,synchronize]
jobs:
  CLAssistant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-regex-match@v2
        id: sign-or-recheck
        with:
          text: ${{ github.event.comment.body }}
          regex: '\s*(I have read the Developer Terms and I hereby accept the terms)|(recheckcla)\s*'
      - name: "CLA Assistant"
        if: ${{ steps.sign-or-recheck.outputs.match != '' || github.event_name == 'pull_request_target' }}
        uses: cla-assistant/github-action@v2.1.1-beta
        env:
          # Generated and maintained by github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # JFrog organization secret
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_SIGN_TOKEN }}
        with:
          path-to-signatures: 'signed_developer_terms.json'
          path-to-document: 'https://github.com/jfrog/jfrog-cli-plugins-reg/blob/master/DEVELOPERS_TERMS.md'
          remote-organization-name: 'jfrog'
          remote-repository-name: 'jfrog-signed-clas'
          # branch should not be protected
          branch: 'master'
          allowlist: bot*
          signed-commit-message: '$contributorName has accepted the Developer Terms in #$pullRequestNo'
          custom-notsigned-prcomment: 'Thank you for your submission, we really appreciate it. We ask that you accept our [JFrog CLI Plugins Developer Terms](https://github.com/jfrog/jfrog-cli-plugins-reg/blob/master/DEVELOPERS_TERMS.md) before we can accept your contribution. You can accept the Terms by just posting a Pull Request Comment same as the below format. Important: we recommend not to copy and paste this message, to avoid including unseen characters, which fail the message validation.'
          custom-pr-sign-comment: 'I have read the Developer Terms and I hereby accept the terms'
          custom-allsigned-prcomment: 'All Contributors have accepted the Developer Terms.'
