name: "Validator Tests"
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  Validator-Tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows, macos]

    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        working-directory: pipelinesScripts/validator
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Go with Cache
        uses: jfrog/.github/actions/install-go-with-cache@main

      - name: Configure git
        run: |
          git config --global user.email "jfrog-ecosystem@jfrog.com"
          git config --global user.name "jfrog-ecosystem"

      - name: Static Code Analysis
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          args: |
            --timeout 5m --enable govet,errcheck,gosimple,ineffassign,staticcheck,typecheck,unused,gocritic,asasalint,asciicheck,errchkjson,copyloopvar,forcetypeassert,makezero,nilerr,unparam,unconvert,wastedassign,usestdlibvars,gosec
          working-directory: pipelinesScripts/validator

      - name: Test Validator
        run: |
          # Run tests
          go test -v ./... -timeout 0 -race
